In [18]:
from numpy import *
A = array([1,2,3])
A

array([1, 2, 3])

In [19]:
M = mat(A)
M

matrix([[1, 2, 3]])

In [20]:
A**2

array([1, 4, 9], dtype=int32)

In [21]:
dot(A,A)

14

In [22]:
multiply(A, A)

array([1, 4, 9])

In [23]:
M**2

LinAlgError: Last 2 dimensions of the array must be square

In [16]:
dot(M,M)

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [17]:
multiply(M, M)

matrix([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])